# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PROVA.xdc

# Block Designs: bd/Prova/Prova.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Prova || ORIG_REF_NAME==Prova} -quiet] -quiet

# IP: bd/Prova/ip/Prova_processing_system7_0_0/Prova_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Prova_processing_system7_0_0 || ORIG_REF_NAME==Prova_processing_system7_0_0} -quiet] -quiet

# IP: bd/Prova/ip/Prova_prova_ip_0_1/Prova_prova_ip_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Prova_prova_ip_0_1 || ORIG_REF_NAME==Prova_prova_ip_0_1} -quiet] -quiet

# IP: bd/Prova/ip/Prova_ps7_0_axi_periph_0/Prova_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Prova_ps7_0_axi_periph_0 || ORIG_REF_NAME==Prova_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Prova/ip/Prova_rst_ps7_0_100M_0/Prova_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Prova_rst_ps7_0_100M_0 || ORIG_REF_NAME==Prova_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Prova/ip/Prova_auto_pc_0/Prova_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Prova_auto_pc_0 || ORIG_REF_NAME==Prova_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/Claudio/project_1/project_1.gen/sources_1/bd/Prova/Prova_ooc.xdc
